/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <unistd.h>
#include <fcntl.h>
#include <stdio.h>

#include <gnome.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
	GtkWidget *print_scale;

	char c;
	int ps2w[2],pw2s[2];

        // 管線s/w是把前端 -> 後端
	pipe(ps2w);
	// 管線w/s是把後端 -> 前端
	pipe(pw2s);
	
	if(fork() > 0)
	{
		/* 母程序, 介面端 */
		
		//把母程序的“標準輸出”轉向給管線s/w中的“輸出”
		dup2(ps2w[1],1);
		//把母程序的“標準輸入”轉向給管線w/s中的“輸入”
		dup2(pw2s[0],0);
		//把母程序中的管線s/w“輸入”關了
		close(ps2w[0]);
		//把母程序中的管線w/s“輸出”關了
		close(pw2s[1]);
		//會停一下的原因是因為要等背景程式的執行
		sleep( 1 );
		//把please input the address 這一行消除掉！
		while( (c = getchar()) != '\n');


  
#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gnome_program_init (PACKAGE, VERSION, LIBGNOMEUI_MODULE,
                      argc, argv,
                      GNOME_PARAM_APP_DATADIR, PACKAGE_DATA_DIR,
                      NULL);

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
	print_scale = create_print_scale ();
	gtk_widget_show (print_scale);
//  about = create_about ();
//  gtk_widget_show (about);

	gtk_main ();
  //return 0;
	}
	else
	{
		/* 子程序, 磅秤端 */
		//把子程序的“標準輸入”轉向到管線s/w中“輸入”
		dup2(ps2w[0],0);
		//把子程序的“標準輸出”轉向到管線w/s中“輸出”
		dup2(pw2s[1],1);
		//把子程序中的管線s/w“輸出”關了
		close(ps2w[1]);
		//把子程序中的管線w/s“輸入”關了
		close(pw2s[0]);
		execl("/home/allways/test3.pl",NULL);
	}
	return 0;
}	                                                      

